add automountServiceAccountToken to helm chart
mittwald/kubernetes-replicator pull request #202
Opened 2022-07-04 13:41 UTC by guethb

We need the automountServiceAccountToken option for deployment and serviceAccount in k8s. Please consider this pull request, adding these entries to kubernetes-replicator helm chart.

2022-07-14 06:18 UTC, martin-helmich requested changes

2022-07-14 06:18 UTC, martin-helmich commented on deploy/helm-chart/kubernetes-replicator/templates/rbac.yaml
> +  automountServiceAccountToken: {{ include kubernetes-replicator.serviceAccount.automountServiceAccountToken" . }}
According to the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server), `.automountServiceAccountToken` is a root-level field, and not a metadata property.

2022-07-14 06:18 UTC, martin-helmich commented on deploy/helm-chart/kubernetes-replicator/templates/deployment.yaml
> +      automountServiceAccountToken: {{ include "kubernetes-replicator.automountServiceAccountToken" . }}
You're calling a macro called `"kubernetes-replicator.automountServiceAccountToken"` here, which is defined nowhere. Please either define the macro or just use `.Values.automountServiceAccountToken` directly.

2022-07-14 06:18 UTC, martin-helmich commented on deploy/helm-chart/kubernetes-replicator/Chart.yaml
> +appVersion: v2.7.4
Bumping the app/chart version manually is not necessary; this will be done by our release scripts when a new version is actually released.

2022-07-29 02:13 UTC, mittwald-machine commented
There has not been any activity to this pull request in the last 14 days. It will automatically be closed after 7 more days. Remove the `stale` label to prevent this.

2022-08-01 07:51 UTC, guethb commented
Please remove stale label.

2022-08-01 07:55 UTC, guethb commented
@martin-helmich I made the changes you requested. Could you please review them and remove the stale label from my PR?

2022-08-01 07:58 UTC, martin-helmich approved these changes
LGTM :+1: -- thanks for your contribution.

2022-08-01 08:01 UTC, merged